[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "streamlit-extras>=0.5.0",
    "streamlit>=1.41.1",
    "streamlit-lottie>=0.0.5",
]
